version: '3.8'

services:
  pinemcp:
    build: .
    container_name: pinemcp
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    stdin_open: true
    tty: true
